/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-12-30 00:29:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin_005fview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_002dproduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\" />\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\n");
      out.write("<title>Add Product - Dashboard HTML Template</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Roboto:400,700\" />\n");
      out.write("<!-- https://fonts.google.com/specimen/Roboto -->\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/admin/css/fontawesome.min.css\" />\n");
      out.write("<!-- https://fontawesome.com/ -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"../resources/admin/jquery-ui-datepicker/jquery-ui.min.css\"\n");
      out.write("\ttype=\"text/css\" />\n");
      out.write("<!-- http://api.jqueryui.com/datepicker/ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/admin/css/bootstrap.min.css\" />\n");
      out.write("<!-- https://getbootstrap.com/ -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"../resources/admin/css/templatemo-style.css\">\n");
      out.write("\n");
      out.write("<!--\n");
      out.write("\tProduct Admin CSS Template\n");
      out.write("\thttps://templatemo.com/tm-524-product-admin\n");
      out.write("\t-->\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-xl\">\n");
      out.write("\t\t\t<div class=\"container h-100\">\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"adminmain.do\">\n");
      out.write("\t\t\t\t\t<h1 class=\"tm-site-title mb-0\">VITAMIN Admin</h1>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler ml-auto mr-0\" type=\"button\"\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\n");
      out.write("\t\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("\t\t\t\t\taria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-bars tm-nav-icon\"></i>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav mx-auto h-100\">\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"adminmain.do\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-tachometer-alt\"></i> Dashboard <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"sr-only\">(current)</span>\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"adminorder.do\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-list-alt\"></i> order <span class=\"sr-only\">(current)</span>\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("<!-- \t\t\t\t\t\t<li class=\"nav-item dropdown\"><a -->\n");
      out.write("<!-- \t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" -->\n");
      out.write("<!-- \t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" -->\n");
      out.write("<!-- \t\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fas fa-chart-bar\"></i> <span> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\tChart <i class=\"fas fa-angle-down\"></i> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t</span> -->\n");
      out.write("<!-- \t\t\t\t\t\t</a> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\"> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Daily Chart</a> <a -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Weekly Chart</a> <a -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Yearly Chart</a> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t</div></li> -->\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\"\n");
      out.write("\t\t\t\t\t\t\thref=\"products.do?category=아령,덤벨\"> <i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fas fa-shopping-cart\"></i> Products\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"accounts.do\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"far fa-user\"></i> Accounts\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown\"><a\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fas fa-cog\"></i> <span>\n");
      out.write("\t\t\t\t\t\t\t\t\tSettings <i class=\"fas fa-angle-down\"></i>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Profile</a> <a\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Billing</a> <a\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Customize</a>\n");
      out.write("\t\t\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav\">\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link d-block\"\n");
      out.write("\t\t\t\t\t\t\thref=\"../homepage.do\"> Admin, <b>Logout</b>\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\t<div class=\"container tm-mt-big tm-mb-big\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<div class=\"col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto\">\n");
      out.write("\t\t\t\t<div class=\"tm-bg-primary-dark tm-block tm-block-h-auto\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"tm-block-title d-inline-block\">상품 추가</h2>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<form action=\"insertproduct.do\" class=\"tm-edit-product-form\" method=\"post\"\n");
      out.write("\t\t\t\t\t\tenctype=\"multipart/form-data\" id = \"productregist\" >\n");
      out.write("\t\t\t\t\t\t<div class=\"row tm-edit-product-row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xl-6 col-lg-6 col-md-12\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group mb-3\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"p_name\">상품명</label> <input id=\"p_name\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"p_name\" type=\"text\" class=\"form-control validate\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\trequired />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group mb-3\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"ca_largecate\">카테고리- 대분류</label> <select\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"custom-select tm-select-accounts form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"ca_largecate\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option selected>대분류 선택</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"헬스용품\">헬스용품</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"요가/필라테스\">요가/필라테스</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"운동복\">운동복</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"건강식품\">건강식품</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group mb-3\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"ca_smallcate\">카테고리 - 소분류</label> <select\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"custom-select tm-select-accounts form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"ca_smallcate\" name = \"ca_smallcate\" required>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t<option selected>소분류 선택</option> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t<option value=\"1\">......1</option> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t<option value=\"2\">......2</option> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t<option value=\"3\">......3</option> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t<div class=\"form-group mb-3 col-xs-12 col-sm-9\"> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t<label for=\"expire_date\">Expire Date </label> <input -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t\tid=\"expire_date\" name=\"expire_date\" type=\"text\" -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t\tclass=\"form-control validate\" data-large-mode=\"true\" /> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t</div> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\" id=\"productprice\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-3 col-xs-12 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"p_costprice\">원가 </label> <input id=\"p_costprice\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"p_costprice\" type=\"number\" class=\"form-control validate\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tdata-large-mode=\"true\" required/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-3 col-xs-12 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"p_discountrate\">할인율 </label> <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"p_discountrate\" name=\"p_discountrate\" type=\"number\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control validate\" min=\"0\" max =\"100\" required />\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-3 col-xs-12 col-sm-6\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"productstock\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"p_sellprice\">판매가 </label> <input id=\"p_sellprice\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"p_sellprice\" type=\"number\" class=\"form-control validate\" readonly/>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-3 col-xs-12 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"p_stock\">재고</label> <input id=\"p_stock\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"p_stock\" type=\"number\" class=\"form-control validate\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trequired />\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group mb-3 col-xs-12 col-sm-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"\"></label>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xl-6 col-lg-6 col-md-12 mx-auto mb-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tm-product-img-dummy mx-auto\" id = \"img_wrap\" style = \"overflow : hidden;\">\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t<i class=\"fas fa-cloud-upload-alt tm-upload-icon\" -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\t\tonclick=\"document.getElementById('mainfile').click();\"></i> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"img_wrap\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img id=\"img\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"custom-file mt-3 mb-3 col-sm-12 \">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"mainfile\" type=\"file\" name=\"mainfile\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control validate\" style = \"display : none; \" required/> <input type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary btn-block mx-auto\" value=\"메인이미지 업로드\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"document.getElementById('mainfile').click();\" />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group mb-3 col-xs-12 col-sm-6\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"custom-file mt-3 mb-3 col-sm-12\" >\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"subfileInput\" multiple=\"multiple\" type=\"file\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"subfileInput\" class=\"form-control\"  style = \"display : none;\" required/> <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"button\" class=\"btn btn-primary btn-block mx-auto\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"설명이미지 업로드\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"document.getElementById('subfileInput').click();\" />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div id = \"imgs\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"imgs_wraps\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group mb-12 col-xs-12 col-sm-12\"\n");
      out.write("\t\t\t\t\t\t\t\t>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-lg-12 col-md-12\">\n");
      out.write("\t\t\t\t\t\t\t\t<input\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary btn-block text-uppercase form-group mb-3 col-xs-6 col-sm-1\"\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"button\" value=\"옵션 추가\" id=\"optionbutton\" /> \n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div id = \"optionlist\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"p_content\">내용</label>\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"form-control validate\" rows=\"6\"\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"p_content\" id=\"p_content\"></textarea>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-12\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" onsubmit=\"return false\" \n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary btn-block text-uppercase\" id = \"productinsert\" value = '상품 등록'>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<footer class=\"tm-footer row tm-mt-small\">\n");
      out.write("\t\t<div class=\"col-12 font-weight-light\">\n");
      out.write("\t\t\t<p class=\"text-center text-white mb-0 px-4 small\">\n");
      out.write("\t\t\t\tCopyright &copy; <b>2018</b> All rights reserved. Design: <a\n");
      out.write("\t\t\t\t\trel=\"nofollow noopener\" href=\"https://templatemo.com\"\n");
      out.write("\t\t\t\t\tclass=\"tm-footer-link\">Template Mo</a>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</footer>\n");
      out.write("\n");
      out.write("\t<script src=\"../resources/admin/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("\t<!-- https://jquery.com/download/ -->\n");
      out.write("\t<script src=\"../resources/admin/jquery-ui-datepicker/jquery-ui.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"../resources/admin/js/adminproduct.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- https://jqueryui.com/download/ -->\n");
      out.write("\t<script src=\"../resources/admin/js/bootstrap.min.js\"></script>\n");
      out.write("\t<!-- https://getbootstrap.com/ -->\n");
      out.write("\t<script>\n");
      out.write("\t\t$(function() {\n");
      out.write("\t\t\t$(\"#expire_date\").datepicker();\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
