/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-12-28 15:57:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin_005fview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminmains_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\n");
      out.write("<title>Product Admin - Dashboard HTML Template</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Roboto:400,700\">\n");
      out.write("<!-- https://fonts.google.com/specimen/Roboto -->\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/admin/css/fontawesome.min.css\">\n");
      out.write("<!-- https://fontawesome.com/ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/admin/css/bootstrap.min.css\">\n");
      out.write("<!-- https://getbootstrap.com/ -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"../resources/admin/css/templatemo-style.css\">\n");
      out.write("<!--\n");
      out.write("\tProduct Admin CSS Template\n");
      out.write("\thttps://templatemo.com/tm-524-product-admin\n");
      out.write("\t-->\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("\tsrc=\"https://www.gstatic.com/charts/loader.js\"></script>\n");
      out.write("\t<script src=\"../resources/admin/js/adminchart.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body id=\"reportsPage\">\n");
      out.write("\t<div class=\"\" id=\"home\">\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-xl\">\n");
      out.write("\t\t\t<div class=\"container h-100\">\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"adminmain.do\">\n");
      out.write("\t\t\t\t\t<h1 class=\"tm-site-title mb-0\">VITAMIN Admin</h1>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler ml-auto mr-0\" type=\"button\"\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\n");
      out.write("\t\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("\t\t\t\t\taria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-bars tm-nav-icon\"></i>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav mx-auto h-100\">\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\"\n");
      out.write("\t\t\t\t\t\t\thref=\"adminmain.do\"> <i class=\"fas fa-tachometer-alt\"></i>\n");
      out.write("\t\t\t\t\t\t\t\tDashboard <span class=\"sr-only\">(current)</span>\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"adminorder.do\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-list-alt\"></i> order <span class=\"sr-only\">(current)</span>\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown\"><a\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fas fa-chart-bar\"></i> <span>\n");
      out.write("\t\t\t\t\t\t\t\t\tChart <i class=\"fas fa-angle-down\"></i>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Daily Chart</a> <a\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Weekly Chart</a> <a\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Yearly Chart</a>\n");
      out.write("\t\t\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\thref=\"products.do?category=아령,덤벨\"> <i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fas fa-shopping-cart\"></i> Products\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"accounts.do\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"far fa-user\"></i> Accounts\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown\"><a\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fas fa-cog\"></i> <span>\n");
      out.write("\t\t\t\t\t\t\t\t\tSettings <i class=\"fas fa-angle-down\"></i>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Profile</a> <a\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Billing</a> <a\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Customize</a>\n");
      out.write("\t\t\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav\">\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link d-block\"\n");
      out.write("\t\t\t\t\t\t\thref=\"../homepage.do\"> Admin, <b>Logout</b>\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col\">\n");
      out.write("\t\t\t\t\t<p class=\"text-white mt-5 mb-5\">\n");
      out.write("\t\t\t\t\t\tWelcome back, <b>Admin</b>\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- row -->\n");
      out.write("\t\t\t<div class=\"row tm-content-row\">\n");
      out.write("\t\t\t\t<div class=\"col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col\">\n");
      out.write("\t\t\t\t\t<div class=\"tm-bg-primary-dark tm-block\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"tm-block-title\">월별 매출</h2>\n");
      out.write("\t\t\t\t\t\t<div id=\"chart_div\"></div>\n");
      out.write("<!-- \t\t\t\t\t\t<canvas id=\"lineChart\"></canvas> -->\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col\">\n");
      out.write("\t\t\t\t\t<div class=\"tm-bg-primary-dark tm-block\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"tm-block-title\">라인 차트</h2>\n");
      out.write("\t\t\t\t\t\t<canvas id=\"lineChart\"></canvas>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col\">\n");
      out.write("\t\t\t\t\t<div class=\"tm-bg-primary-dark tm-block\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"tm-block-title\">판매</h2>\n");
      out.write("\t\t\t\t\t\t<canvas id=\"barChart\"></canvas>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col\">\n");
      out.write("\t\t\t\t\t<div class=\"tm-bg-primary-dark tm-block tm-block-taller\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"tm-block-title\">Storage Information</h2>\n");
      out.write("\t\t\t\t\t\t<div id=\"pieChartContainer\">\n");
      out.write("\t\t\t\t\t\t\t<canvas id=\"pieChart\" class=\"chartjs-render-monitor\" width=\"200\"\n");
      out.write("\t\t\t\t\t\t\t\theight=\"200\"></canvas>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-sm-12 col-md-12 col-lg-6 col-xl-6 tm-block-col\">\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"tm-bg-primary-dark tm-block tm-block-taller tm-block-overflow\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"tm-block-title\">Notification List</h2>\n");
      out.write("\t\t\t\t\t\t<div class=\"tm-notification-items\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media tm-notification-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tm-gray-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../resources/admin/img/notification-01.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Avatar Image\" class=\"rounded-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Jessica</b> and <b>6 others</b> sent you new <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"tm-notification-link\">product updates</a>. Check new\n");
      out.write("\t\t\t\t\t\t\t\t\t\torders.\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media tm-notification-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tm-gray-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../resources/admin/img/notification-02.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Avatar Image\" class=\"rounded-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Oliver Too</b> and <b>6 others</b> sent you existing <a\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"#\" class=\"tm-notification-link\">product updates</a>.\n");
      out.write("\t\t\t\t\t\t\t\t\t\tRead more reports.\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media tm-notification-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tm-gray-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../resources/admin/img/notification-03.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Avatar Image\" class=\"rounded-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Victoria</b> and <b>6 others</b> sent you <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"tm-notification-link\">order updates</a>. Read order\n");
      out.write("\t\t\t\t\t\t\t\t\t\tinformation.\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media tm-notification-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tm-gray-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../resources/admin/img/notification-01.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Avatar Image\" class=\"rounded-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Laura Cute</b> and <b>6 others</b> sent you <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"tm-notification-link\">product records</a>.\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media tm-notification-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tm-gray-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../resources/admin/img/notification-02.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Avatar Image\" class=\"rounded-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Samantha</b> and <b>6 others</b> sent you <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"tm-notification-link\">order stuffs</a>.\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media tm-notification-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tm-gray-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../resources/admin/img/notification-03.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Avatar Image\" class=\"rounded-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Sophie</b> and <b>6 others</b> sent you <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"tm-notification-link\">product updates</a>.\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media tm-notification-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tm-gray-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../resources/admin/img/notification-01.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Avatar Image\" class=\"rounded-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Lily A</b> and <b>6 others</b> sent you <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"tm-notification-link\">product updates</a>.\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media tm-notification-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tm-gray-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../resources/admin/img/notification-02.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Avatar Image\" class=\"rounded-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Amara</b> and <b>6 others</b> sent you <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"tm-notification-link\">product updates</a>.\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"media tm-notification-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tm-gray-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"../resources/admin/img/notification-03.jpg\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\talt=\"Avatar Image\" class=\"rounded-circle\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"media-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"mb-2\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<b>Cinthela</b> and <b>6 others</b> sent you <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"tm-notification-link\">product updates</a>.\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"tm-small tm-text-color-secondary\">6h ago.</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-12 tm-block-col\">\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"tm-bg-primary-dark tm-block tm-block-taller tm-block-scroll\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"tm-block-title\">Orders List</h2>\n");
      out.write("\t\t\t\t\t\t<table class=\"table\">\n");
      out.write("\t\t\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">ORDER NO.</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">STATUS</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">OPERATORS</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">LOCATION</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">DISTANCE</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">START DATE</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"col\">EST DELIVERY DUE</th>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\t\t<tbody>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\"><b>#122349</b></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tm-status-circle moving\"></div>Moving\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Oliver Trag</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>London, UK</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>485 km</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>16:00, 12 NOV 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>08:00, 18 NOV 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\"><b>#122348</b></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tm-status-circle pending\"></div>Pending\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Jacob Miller</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>London, UK</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>360 km</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>11:00, 10 NOV 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>04:00, 14 NOV 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\"><b>#122347</b></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tm-status-circle cancelled\"></div>Cancelled\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>George Wilson</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>London, UK</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>340 km</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>12:00, 22 NOV 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>06:00, 28 NOV 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\"><b>#122346</b></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tm-status-circle moving\"></div>Moving\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>William Aung</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>London, UK</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>218 km</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>15:00, 10 NOV 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>09:00, 14 NOV 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\"><b>#122345</b></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tm-status-circle pending\"></div>Pending\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Harry Ryan</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>London, UK</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>280 km</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>15:00, 11 NOV 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>09:00, 17 NOV 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\"><b>#122344</b></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tm-status-circle pending\"></div>Pending\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Michael Jones</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>London, UK</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>218 km</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>18:00, 12 OCT 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>06:00, 18 OCT 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\"><b>#122343</b></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tm-status-circle moving\"></div>Moving\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Timmy Davis</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>London, UK</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>218 km</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>12:00, 10 OCT 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>08:00, 18 OCT 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\"><b>#122342</b></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tm-status-circle moving\"></div>Moving\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Oscar Phyo</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>London, UK</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>420 km</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>15:30, 06 OCT 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>09:30, 16 OCT 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\"><b>#122341</b></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tm-status-circle moving\"></div>Moving\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Charlie Brown</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>London, UK</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>300 km</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>11:00, 10 OCT 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>03:00, 14 OCT 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\"><b>#122340</b></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tm-status-circle cancelled\"></div>Cancelled\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Wilson Cookies</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>London, UK</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>218 km</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>17:30, 12 OCT 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>08:30, 22 OCT 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t<th scope=\"row\"><b>#122339</b></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tm-status-circle moving\"></div>Moving\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>Richard Clamon</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>London, UK</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><b>150 km</b></td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>15:00, 12 OCT 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>09:20, 26 OCT 2018</td>\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<footer class=\"tm-footer row tm-mt-small\">\n");
      out.write("\t\t\t<div class=\"col-12 font-weight-light\">\n");
      out.write("\t\t\t\t<p class=\"text-center text-white mb-0 px-4 small\">\n");
      out.write("\t\t\t\t\tCopyright &copy; <b>2018</b> All rights reserved. Design: <a\n");
      out.write("\t\t\t\t\t\trel=\"nofollow noopener\" href=\"https://templatemo.com\"\n");
      out.write("\t\t\t\t\t\tclass=\"tm-footer-link\">Template Mo</a>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</footer>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script src=\"../resources/admin/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("\t<!-- https://jquery.com/download/ -->\n");
      out.write("\t<script src=\"../resources/admin/js/moment.min.js\"></script>\n");
      out.write("\t<!-- https://momentjs.com/ -->\n");
      out.write("\t<script src=\"../resources/admin/js/Chart.min.js\"></script>\n");
      out.write("\t<!-- http://www.chartjs.org/docs/latest/ -->\n");
      out.write("\t<script src=\"../resources/admin/js/bootstrap.min.js\"></script>\n");
      out.write("\t<!-- https://getbootstrap.com/ -->\n");
      out.write("\t<script src=\"../resources/admin/js/tooplate-scripts.js\"></script>\n");
      out.write("\n");
      out.write("\t<script>\n");
      out.write("\t\tChart.defaults.global.defaultFontColor = 'white';\n");
      out.write("\t\tlet ctxLine, ctxBar, ctxPie, optionsLine, optionsBar, optionsPie, configLine, configBar, configPie, lineChart;\n");
      out.write("\t\tbarChart, pieChart;\n");
      out.write("\t\t// DOM is ready\n");
      out.write("\t\t$(function() {\n");
      out.write("\t\t\tdrawLineChart(); // Line Chart\n");
      out.write("\t\t\tdrawBarChart(); // Bar Chart\n");
      out.write("\t\t\tdrawPieChart(); // Pie Chart\n");
      out.write("\n");
      out.write("\t\t\t$(window).resize(function() {\n");
      out.write("\t\t\t\tupdateLineChart();\n");
      out.write("\t\t\t\tupdateBarChart();\n");
      out.write("\t\t\t});\n");
      out.write("\t\t})\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
