/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2020-12-31 05:42:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin_005fview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class orderdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1608100594860L));
    _jspx_dependants.put("jar:file:/D:/spring/web/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/VITAMIN/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\" />\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\" />\n");
      out.write("<title>Accounts - Product Admin Template</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Roboto:400,700\" />\n");
      out.write("<!-- https://fonts.google.com/specimen/Roboto -->\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/admin/css/fontawesome.min.css\" />\n");
      out.write("<!-- https://fontawesome.com/ -->\n");
      out.write("<link rel=\"stylesheet\" href=\"../resources/admin/css/bootstrap.min.css\" />\n");
      out.write("<!-- https://getbootstrap.com/ -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"../resources/admin/css/templatemo-style.css\">\n");
      out.write("<!--\n");
      out.write("\tProduct Admin CSS Template\n");
      out.write("\thttps://templatemo.com/tm-524-product-admin\n");
      out.write("\t-->\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body id=\"reportsPage\">\n");
      out.write("\t<div class=\"\" id=\"home\">\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-xl\">\n");
      out.write("\t\t\t<div class=\"container h-100\">\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"adminmain.do\">\n");
      out.write("\t\t\t\t\t<h1 class=\"tm-site-title mb-0\">VITAMIN Admin</h1>\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<button class=\"navbar-toggler ml-auto mr-0\" type=\"button\"\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\n");
      out.write("\t\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("\t\t\t\t\taria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t\t\t<i class=\"fas fa-bars tm-nav-icon\"></i>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav mx-auto h-100\">\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"adminmain.do\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fas fa-tachometer-alt\"></i> Dashboard <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"sr-only\">(current)</span>\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\"\n");
      out.write("\t\t\t\t\t\t\thref=\"adminorder.do\"> <i class=\"fas fa-list-alt\"></i> order <span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"sr-only\">(current)</span>\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t<li class=\"nav-item dropdown\"><a -->\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" -->\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" -->\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fas fa-chart-bar\"></i> <span> -->\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\tChart <i class=\"fas fa-angle-down\"></i> -->\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t</span> -->\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t</a> -->\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\"> -->\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Daily Chart</a> <a -->\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Weekly Chart</a> <a -->\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Yearly Chart</a> -->\n");
      out.write("\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t</div></li> -->\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\"\n");
      out.write("\t\t\t\t\t\t\thref=\"products.do?category=아령,덤벨\"> <i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fas fa-shopping-cart\"></i> Products\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"accounts.do\">\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"far fa-user\"></i> Accounts\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item dropdown\"><a\n");
      out.write("\t\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\n");
      out.write("\t\t\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\n");
      out.write("\t\t\t\t\t\t\taria-expanded=\"false\"> <i class=\"fas fa-cog\"></i> <span>\n");
      out.write("\t\t\t\t\t\t\t\t\tSettings <i class=\"fas fa-angle-down\"></i>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Profile</a> <a\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Billing</a> <a\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Customize</a>\n");
      out.write("\t\t\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t<ul class=\"navbar-nav\">\n");
      out.write("\t\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link d-block\"\n");
      out.write("\t\t\t\t\t\t\thref=\"../homepage.do\"> Admin, <b>Logout</b>\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t<div class=\"container mt-5\">\n");
      out.write("\t\t\t<!-- 회원 명단 -->\n");
      out.write("\t\t\t<div class=\"row tm-content-row\">\n");
      out.write("\t\t\t\t<div class=\"col-12 tm-block-col\">\n");
      out.write("\t\t\t\t\t<div class=\"tm-bg-primary-dark tm-block tm-block-h-auto\">\n");
      out.write("\t\t\t\t\t\t<h2 class=\"tm-block-title\">주문 조회</h2>\n");
      out.write("\t\t\t\t\t\t<div class=\"tm-signup-form row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-lg-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"name\">주문 번호</label> <input id=\"name\" name=\"name\"\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control validate\" value = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${O_NUM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("   readonly />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-lg-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"name\">받는사람</label> <input id=\"name\" name=\"name\"\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control validate\" value = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${O_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" readonly />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-lg-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"name\">주문일</label> <input id=\"name\" name=\"name\"\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control validate\" value = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${O_DATE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" readonly />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-lg-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"name\">전화번호</label> <input id=\"name\" name=\"name\"\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control validate\"  value = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${O_TEL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" readonly />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-lg-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"name\">주소</label> <input id=\"name\" name=\"name\"\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control validate\" value = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${O_ADD}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" readonly />\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-lg-4\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"name\">배송상태</label> <input id=\"name\" name=\"name\"\n");
      out.write("\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control validate\" value = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${O_DELIVERY}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" readonly />\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group col-lg-4\"  style='position: absolute; top:40px; left:200px;'>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!-- \t\t\t\t\t\t\t\t<input id=\"name\" name=\"name\" -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control validate\" readonly /> -->\n");
      out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- row -->\n");
      out.write("\t\t\t\t<div class=\"row tm-content-row\">\n");
      out.write("\t\t\t\t\t<div class=\"tm-block-col tm-col-avatar\">\n");
      out.write("\t\t\t\t\t\t<div class=\"tm-bg-primary-dark tm-block tm-block-avatar\">\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"tm-block-title\"></h2>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"tm-avatar-container\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../resources/admin/product/mainimages/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${P_MAINIMAGE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"Avatar\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"tm-avatar img-fluid mb-4\" /> <a href=\"#\"\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"tm-avatar-delete-link\"> <i\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"far fa-trash-alt tm-product-delete-icon\"></i>\n");
      out.write("\t\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("<!-- \t\t\t\t\t\t\t<button class=\"btn btn-primary btn-block text-uppercase\"> -->\n");
      out.write("<!-- \t\t\t\t\t\t\t\t부트스트랩 진짜 싫다</button> -->\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"tm-block-col tm-col-account-settings\">\n");
      out.write("\t\t\t\t\t\t<div class=\"tm-bg-primary-dark tm-block tm-block-settings\">\n");
      out.write("\t\t\t\t\t\t\t<h2 class=\"tm-block-title\">상품</h2>\n");
      out.write("\t\t\t\t\t\t\t<form action=\"\" class=\"tm-signup-form row\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group col-lg-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"name\">상품명</label> <input id=\"name\" name=\"name\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control validate\" value = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${P_NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" readonly />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group col-lg-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"trainerid\">개수</label> <input id=\"trainerid\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"trainerid\" type=\"text\" class=\"form-control validate\" value = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${O_COUNT}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\treadonly />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group col-lg-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"desiredpay\">주문금액</label> <input id=\"desiredpay\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"desiredpay\" type=\"text\" class=\"form-control validate\" value = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${O_PRICE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\treadonly />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group col-lg-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"desiredpay\">옵션이름</label> <input id=\"option\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"option\" type=\"text\" class=\"form-control validate\" value = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${PO_OPTIONNAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\treadonly />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group col-lg-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"phone\"></label> <input id=\"phone\" name=\"phone\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"tel\" class=\"form-control validate\" style = \"display : none;\" readonly />\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t<div class=\"form-group col-lg-6\"> -->\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t<label class=\"tm-hide-sm\">&nbsp;</label> -->\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t<button type=\"submit\" -->\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary btn-block text-uppercase\"> -->\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\tUpdate Your Profile</button> -->\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t</div> -->\n");
      out.write("\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t공백주기위함 -->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row row-col-spacer\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\"></div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t    공백주기위함 여기까지 -->\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href = \"adminorder.do\"><button type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-primary btn-block text-uppercase\">목록가기</button></a>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6\" style = \"display : none;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-block text-uppercase btn-danger\">거절</button>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<footer class=\"tm-footer row tm-mt-small\">\n");
      out.write("\t\t\t\t<div class=\"col-12 font-weight-light\">\n");
      out.write("\t\t\t\t\t<p class=\"text-center text-white mb-0 px-4 small\">\n");
      out.write("\t\t\t\t\t\tCopyright &copy; <b>2018</b> All rights reserved. Design: <a\n");
      out.write("\t\t\t\t\t\t\trel=\"nofollow noopener\" href=\"https://templatemo.com\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"tm-footer-link\">Template Mo</a>\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</footer>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<script src=\"../resources/admin/js/jquery-3.3.1.min.js\"></script>\n");
      out.write("\t\t<!-- https://jquery.com/download/ -->\n");
      out.write("\t\t<script type=\"text/javascript\"\n");
      out.write("\t\t\tsrc=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\n");
      out.write("\t\t<script src=\"../resources/admin/js/bootstrap.min.js\"></script>\n");
      out.write("\t\t<script src=\"../resources/admin/js/adminaccount.js\"></script>\n");
      out.write("\t\t<!-- https://getbootstrap.com/ -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/admin_view/orderdetail.jsp(125,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty U_ID}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t<label for=\"name\" id = \"userid\">비회원</label> \n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t<label for=\"name\" id = \"userid\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${U_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" 회원</label> \n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
